// ============================================================
// WOIMS — Supabase Client & Database API
// ============================================================
// Runtime config is generated by scripts/generate-env.js for Vercel.
// Public browser config only. Never place service_role keys here.
// Supabase Dashboard → Settings → API
// ============================================================

const NEXARTWO_ENV = (typeof window !== 'undefined' && window.NEXARTWO_ENV) ? window.NEXARTWO_ENV : {};
const DEFAULT_SUPABASE_URL = 'https://udaeifoibydcokefcmbg.supabase.co';
const DEFAULT_SUPABASE_ANON_KEY = 'sb_publishable_8n5oHdP9MhT3hsZf-IRqiw__b4qcTfC';
const SUPABASE_URL = String(NEXARTWO_ENV.SUPABASE_URL || DEFAULT_SUPABASE_URL).trim();
const SUPABASE_ANON_KEY = String(NEXARTWO_ENV.SUPABASE_ANON_KEY || DEFAULT_SUPABASE_ANON_KEY).trim();
const SUPABASE_EMAIL_FUNCTION_URL = String(
  NEXARTWO_ENV.SUPABASE_EMAIL_FUNCTION_URL ||
  (SUPABASE_URL ? SUPABASE_URL.replace(/\/+$/, '') + '/functions/v1/send-email' : '')
).trim();

let _sb = null;
let _supabaseReady = false;

function getSupabase() {
  if (_sb) return _sb;
  if (typeof supabase === 'undefined' || !supabase.createClient) return null;
  if (SUPABASE_URL.includes('%%') || SUPABASE_ANON_KEY.includes('%%')) {
    console.warn('Supabase credentials not configured. Using localStorage fallback.');
    return null;
  }
  try {
    _sb = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
    _supabaseReady = true;
    return _sb;
  } catch (e) {
    console.error('Supabase init error:', e);
    return null;
  }
}

function isSupabaseReady() {
  return !!getSupabase();
}

function getSupabaseFunctionUrl(functionName) {
  if (functionName === 'send-email' && SUPABASE_EMAIL_FUNCTION_URL) {
    return SUPABASE_EMAIL_FUNCTION_URL;
  }
  if (!SUPABASE_URL || !functionName) return '';
  return SUPABASE_URL.replace(/\/+$/, '') + '/functions/v1/' + String(functionName).replace(/^\/+/, '');
}

// ============================================================
// DATABASE API
// ============================================================
const DB = {

  // ---------- CLIENTS ----------
  clients: {
    async getAll() {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('clients').select('*').order('id', { ascending: true });
      if (error) { console.error('DB clients.getAll:', error); return null; }
      return data.map(function(r) {
        return {
          id: r.id, name: r.name, type: r.type, email: r.email,
          phone: r.phone, address: r.address, referral: r.referral,
          lang: r.lang, payment: r.payment, tags: r.tags, notes: r.notes,
          properties: r.properties || 0,
          totalOrders: r.total_orders || 0,
          totalValue: parseFloat(r.total_value) || 0
        };
      });
    },

    async create(c) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('clients').insert({
        name: c.name, type: c.type, email: c.email, phone: c.phone,
        address: c.address || '', referral: c.referral || '',
        lang: c.lang || 'English', payment: c.payment || 'Net 30',
        tags: c.tags || '', notes: c.notes || '',
        properties: c.properties || 0,
        total_orders: c.totalOrders || 0,
        total_value: c.totalValue || 0
      }).select().single();
      if (error) { console.error('DB clients.create:', error); return null; }
      return data;
    },

    async update(id, changes) {
      var sb = getSupabase();
      if (!sb) return false;
      var row = {};
      if ('name' in changes) row.name = changes.name;
      if ('type' in changes) row.type = changes.type;
      if ('email' in changes) row.email = changes.email;
      if ('phone' in changes) row.phone = changes.phone;
      if ('address' in changes) row.address = changes.address;
      if ('referral' in changes) row.referral = changes.referral;
      if ('lang' in changes) row.lang = changes.lang;
      if ('payment' in changes) row.payment = changes.payment;
      if ('tags' in changes) row.tags = changes.tags;
      if ('notes' in changes) row.notes = changes.notes;
      if ('properties' in changes) row.properties = changes.properties;
      if ('totalOrders' in changes) row.total_orders = changes.totalOrders;
      if ('totalValue' in changes) row.total_value = changes.totalValue;
      row.updated_at = new Date().toISOString();
      var { error } = await sb.from('clients').update(row).eq('id', id);
      if (error) { console.error('DB clients.update:', error); return false; }
      return true;
    },

    async delete(id) {
      var sb = getSupabase();
      if (!sb) return false;
      var { error } = await sb.from('clients').delete().eq('id', id);
      if (error) { console.error('DB clients.delete:', error); return false; }
      return true;
    }
  },

  // ---------- SERVICES ----------
  services: {
    async getAll() {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('services').select('*').order('id', { ascending: true });
      if (error) { console.error('DB services.getAll:', error); return null; }
      return data.map(function(r) {
        return {
          id: r.id, name: r.name, nameEs: r.name_es || '',
          category: r.category, sub: r.sub,
          // Price Book alignment: services.price is operational sell price, equivalent to unit_price in NexArtPro.
          price: parseFloat(r.price) || 0,
          unit: r.unit, desc: r.description || '',
          negotiable: r.negotiable || 'yes',
          laborHrs: parseFloat(r.labor_hrs) || 1,
          serviceType: r.service_type || 'residential'
        };
      });
    },

    async create(s) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('services').insert({
        name: s.name, name_es: s.nameEs || '',
        category: s.category, sub: s.sub,
        price: s.price, unit: s.unit,
        description: s.desc || '',
        negotiable: s.negotiable || 'yes',
        labor_hrs: s.laborHrs || 1,
        service_type: s.serviceType || s.service_type || 'residential'
      }).select().single();
      if (error) { console.error('DB services.create:', error); return null; }
      return data;
    },

    async bulkInsert(services) {
      var sb = getSupabase();
      if (!sb) return false;
      var rows = services.map(function(s) {
        return {
          name: s.name, name_es: s.nameEs || '',
          category: s.category, sub: s.sub,
          price: s.price, unit: s.unit,
          description: s.desc || '',
          negotiable: s.negotiable || 'yes',
          labor_hrs: s.laborHrs || 1,
          service_type: s.serviceType || s.service_type || 'residential'
        };
      });
      var { error } = await sb.from('services').insert(rows);
      if (error) { console.error('DB services.bulkInsert:', error); return false; }
      return true;
    }
  },

  // ---------- WORK ORDERS ----------
  workOrders: {
    async getAll() {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('work_orders').select('*').order('created_at', { ascending: false });
      if (error) { console.error('DB workOrders.getAll:', error); return null; }
      return data.map(function(r) {
        return {
          id: r.id, title: r.title,
          client: r.client_name, clientId: r.client_id,
          property: r.property, type: r.type,
          status: r.status, priority: r.priority,
          created: r.created_date, target: r.target_date || '',
          items: r.items || 0,
          total: parseFloat(r.total) || 0,
          completed: r.completed || 0,
          project_id: r.project_id || null
        };
      });
    },

    async create(wo) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('work_orders').insert({
        id: wo.id, title: wo.title,
        client_name: wo.client, client_id: wo.clientId || null,
        property: wo.property, type: wo.type,
        status: wo.status, priority: wo.priority,
        created_date: wo.created,
        target_date: wo.target || null,
        items: wo.items || 0,
        total: wo.total || 0,
        completed: wo.completed || 0,
        project_id: wo.project_id || null
      }).select().single();
      if (error) { console.error('DB workOrders.create:', error); return null; }
      return data;
    },

    async update(id, changes) {
      var sb = getSupabase();
      if (!sb) return false;
      var row = {};
      if ('title' in changes) row.title = changes.title;
      if ('client' in changes) row.client_name = changes.client;
      if ('clientId' in changes) row.client_id = changes.clientId;
      if ('property' in changes) row.property = changes.property;
      if ('status' in changes) row.status = changes.status;
      if ('priority' in changes) row.priority = changes.priority;
      if ('target' in changes) row.target_date = changes.target;
      if ('items' in changes) row.items = changes.items;
      if ('total' in changes) row.total = changes.total;
      if ('completed' in changes) row.completed = changes.completed;
      if ('project_id' in changes) row.project_id = changes.project_id ?? null;
      row.updated_at = new Date().toISOString();
      var { error } = await sb.from('work_orders').update(row).eq('id', id);
      if (error) { console.error('DB workOrders.update:', error); return false; }
      return true;
    },

    async delete(id) {
      var sb = getSupabase();
      if (!sb) return false;
      var { error } = await sb.from('work_orders').delete().eq('id', id);
      if (error) { console.error('DB workOrders.delete:', error); return false; }
      return true;
    }
  },

  // ---------- COMPANY SETTINGS ----------
  company: {
    async get() {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('company_settings').select('*').limit(1).single();
      if (error && error.code !== 'PGRST116') { console.error('DB company.get:', error); return null; }
      if (!data) return null;
      return {
        name: data.name, owner: data.owner,
        phone: data.phone, email: data.email,
        city: data.city, state: data.state,
        ccb: data.ccb, founded: data.founded,
        address: data.address,
        logo_url: data.logo_url || '',
        app_logo_url: data.app_logo_url || ''
      };
    },

    async save(settings) {
      var sb = getSupabase();
      if (!sb) return false;
      var row = {
        name: settings.name || '', owner: settings.owner || '',
        phone: settings.phone || '', email: settings.email || '',
        city: settings.city || '', state: settings.state || '',
        ccb: settings.ccb || '', founded: settings.founded || '',
        address: settings.address || '',
        logo_url: settings.logo_url || '',
        app_logo_url: settings.app_logo_url || '',
        updated_at: new Date().toISOString()
      };
      // Try update first, then insert
      var { data: existing } = await sb.from('company_settings').select('id').limit(1).single();
      if (existing) {
        var { error } = await sb.from('company_settings').update(row).eq('id', existing.id);
        if (error) { console.error('DB company.save update:', error); return false; }
      } else {
        var { error } = await sb.from('company_settings').insert(row);
        if (error) { console.error('DB company.save insert:', error); return false; }
      }
      return true;
    }
  },

  // ---------- LOGO STORAGE ----------
  logos: {
    async upload(file, filename) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.storage.from('logos').upload(filename, file, {
        cacheControl: '3600',
        upsert: true
      });
      if (error) { console.error('DB logos.upload:', error); return null; }
      var { data: urlData } = sb.storage.from('logos').getPublicUrl(filename);
      return urlData.publicUrl;
    }
  },

  // ---------- LINE ITEMS (Phase 2) ----------
  lineItems: {
    async getByWO(workOrderId) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('wo_line_items').select('*')
        .eq('work_order_id', workOrderId)
        .order('sort_order', { ascending: true });
      if (error) { console.error('DB lineItems.getByWO:', error); return null; }
      return data.map(function(r) {
        return {
          id: r.id, workOrderId: r.work_order_id, serviceId: r.service_id,
          name: r.name, nameEs: r.name_es || '', desc: r.description || '',
          category: r.category, sub: r.sub,
          price: parseFloat(r.price) || 0, qty: parseFloat(r.qty) || 1,
          unit: r.unit, negotiable: r.negotiable || 'yes',
          laborHrs: parseFloat(r.labor_hrs) || 1,
          status: r.status || 'pending',
          completedAt: r.completed_at, completedBy: r.completed_by || '',
          notes: r.notes || '', sortOrder: r.sort_order || 0
        };
      });
    },

    async create(item) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('wo_line_items').insert({
        work_order_id: item.workOrderId,
        service_id: item.serviceId || null,
        name: item.name, name_es: item.nameEs || '',
        description: item.desc || '',
        category: item.category || '', sub: item.sub || '',
        price: item.price || 0, qty: item.qty || 1,
        unit: item.unit || 'each', negotiable: item.negotiable || 'yes',
        labor_hrs: item.laborHrs || 1,
        status: item.status || 'pending',
        notes: item.notes || '',
        sort_order: item.sortOrder || 0
      }).select().single();
      if (error) { console.error('DB lineItems.create:', error); return null; }
      return data;
    },

    async update(id, changes) {
      var sb = getSupabase();
      if (!sb) return false;
      var row = {};
      if ('status' in changes) row.status = changes.status;
      if ('completedAt' in changes) row.completed_at = changes.completedAt;
      if ('completedBy' in changes) row.completed_by = changes.completedBy;
      if ('price' in changes) row.price = changes.price;
      if ('qty' in changes) row.qty = changes.qty;
      if ('notes' in changes) row.notes = changes.notes;
      if ('name' in changes) row.name = changes.name;
      if ('desc' in changes) row.description = changes.desc;
      if ('sortOrder' in changes) row.sort_order = changes.sortOrder;
      var { error } = await sb.from('wo_line_items').update(row).eq('id', id);
      if (error) { console.error('DB lineItems.update:', error); return false; }
      return true;
    },

    async delete(id) {
      var sb = getSupabase();
      if (!sb) return false;
      var { error } = await sb.from('wo_line_items').delete().eq('id', id);
      if (error) { console.error('DB lineItems.delete:', error); return false; }
      return true;
    }
  },

  // ---------- DOCUMENTS (Phase 2) ----------
  documents: {
    async getAll() {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('documents').select('*').order('created_at', { ascending: false });
      if (error) { console.error('DB documents.getAll:', error); return null; }
      return data;
    },

    async create(doc) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('documents').insert({
        doc_number: doc.doc_number, type: doc.type,
        work_order_id: doc.work_order_id, client_name: doc.client_name || '',
        status: doc.status || 'draft', style: doc.style || 'classic',
        hide_prices: doc.hide_prices || false, notes: doc.notes || ''
      }).select().single();
      if (error) { console.error('DB documents.create:', error); return null; }
      return data;
    },

    async update(id, changes) {
      var sb = getSupabase();
      if (!sb) return false;
      var { error } = await sb.from('documents').update(changes).eq('id', id);
      if (error) { console.error('DB documents.update:', error); return false; }
      return true;
    }
  },

  // ---------- COMMUNICATIONS (Phase 2) ----------
  communications: {
    async getByWO(workOrderId) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('wo_communications').select('*')
        .eq('work_order_id', workOrderId)
        .order('created_at', { ascending: false });
      if (error) { console.error('DB communications.getByWO:', error); return null; }
      return data;
    },

    async create(comm) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('wo_communications').insert({
        work_order_id: comm.work_order_id,
        type: comm.type || 'note',
        subject: comm.subject || '',
        body: comm.body || '',
        sender: comm.sender || '',
        recipient: comm.recipient || ''
      }).select().single();
      if (error) { console.error('DB communications.create:', error); return null; }
      return data;
    }
  },

  // ---------- CHANGE ORDERS (Phase 2) ----------
  changeOrders: {
    async getByWO(workOrderId) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('change_orders').select('*')
        .eq('work_order_id', workOrderId)
        .order('created_at', { ascending: false });
      if (error) { console.error('DB changeOrders.getByWO:', error); return null; }
      return data;
    },

    async create(co) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('change_orders').insert({
        co_number: co.co_number,
        work_order_id: co.work_order_id,
        description: co.description || '',
        items: co.items || [],
        amount: co.amount || 0,
        status: co.status || 'proposed',
        requested_by: co.requested_by || ''
      }).select().single();
      if (error) { console.error('DB changeOrders.create:', error); return null; }
      return data;
    },

    async update(id, changes) {
      var sb = getSupabase();
      if (!sb) return false;
      var { error } = await sb.from('change_orders').update(changes).eq('id', id);
      if (error) { console.error('DB changeOrders.update:', error); return false; }
      return true;
    }
  },

  // ---------- PHOTOS (Phase 2) ----------
  photos: {
    async getByWO(workOrderId) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('wo_photos').select('*')
        .eq('work_order_id', workOrderId)
        .order('created_at', { ascending: false });
      if (error) { console.error('DB photos.getByWO:', error); return null; }
      return data;
    },

    async create(photo) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('wo_photos').insert({
        work_order_id: photo.work_order_id,
        type: photo.type || 'before',
        label: photo.label || '',
        area: photo.area || '',
        photo_url: photo.photo_url || '',
        gps_lat: photo.gps_lat || null,
        gps_lng: photo.gps_lng || null,
        taken_by: photo.taken_by || ''
      }).select().single();
      if (error) { console.error('DB photos.create:', error); return null; }
      return data;
    },

    async uploadFile(file, workOrderId) {
      var sb = getSupabase();
      if (!sb) return null;
      var filename = workOrderId + '/' + Date.now() + '_' + file.name;
      var { data, error } = await sb.storage.from('photos').upload(filename, file, {
        cacheControl: '3600', upsert: false
      });
      if (error) { console.error('DB photos.uploadFile:', error); return null; }
      var { data: urlData } = sb.storage.from('photos').getPublicUrl(filename);
      return urlData.publicUrl;
    }
  },

  // ---------- PROJECTS (Phase 2) ----------
  projects: {
    async getAll() {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('projects').select('*').order('created_at', { ascending: false });
      if (error) { console.error('DB projects.getAll:', error); return null; }
      return data;
    },
    async getById(id) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('projects').select('*').eq('id', id).single();
      if (error) { console.error('DB projects.getById:', error); return null; }
      return data;
    },
    async create(p) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('projects').insert(p).select().single();
      if (error) { console.error('DB projects.create:', error); return null; }
      return data;
    },
    async update(id, changes) {
      var sb = getSupabase();
      if (!sb) return false;
      changes.updated_at = new Date().toISOString();
      var { error } = await sb.from('projects').update(changes).eq('id', id);
      if (error) { console.error('DB projects.update:', error); return false; }
      return true;
    },
    async cancel(id) {
      // RULE 14: Never delete. We change status to cancelled.
      var sb = getSupabase();
      if (!sb) return false;
      var { error } = await sb.from('projects').update({ status: 'cancelled', updated_at: new Date().toISOString() }).eq('id', id);
      if (error) { console.error('DB projects.cancel:', error); return false; }
      return true;
    }
  },

  // ---------- PROJECT EXPENSES (Phase 2) ----------
  projectExpenses: {
    async getByProject(projectId) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('project_expenses').select('*').eq('project_id', projectId).order('created_at', { ascending: false });
      if (error) { console.error('DB projectExpenses.getByProject:', error); return null; }
      return data;
    },
    async create(ex) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('project_expenses').insert(ex).select().single();
      if (error) { console.error('DB projectExpenses.create:', error); return null; }
      return data;
    },
    async updateStatus(id, status, notes) {
      var sb = getSupabase();
      if (!sb) return false;
      var payload = { status: status };
      if (notes !== undefined) payload.rejection_reason = notes;
      var { error } = await sb.from('project_expenses').update(payload).eq('id', id);
      if (error) { console.error('DB projectExpenses.updateStatus:', error); return false; }
      return true;
    },
    async updateNotes(id, notes) {
      var sb = getSupabase();
      if (!sb) return false;
      var { error } = await sb.from('project_expenses').update({ notes: notes }).eq('id', id);
      if (error) { console.error('DB projectExpenses.updateNotes:', error); return false; }
      return true;
    }
  },

  // ---------- PROJECT REFUNDS (Phase 2) ----------
  projectRefunds: {
    async getByProject(projectId) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('project_refunds').select('*').eq('project_id', projectId).order('created_at', { ascending: false });
      if (error) { console.error('DB projectRefunds.getByProject:', error); return null; }
      return data;
    },
    async create(rf) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('project_refunds').insert(rf).select().single();
      if (error) { console.error('DB projectRefunds.create:', error); return null; }
      return data;
    },
    async updateStatus(id, status) {
      var sb = getSupabase();
      if (!sb) return false;
      var { error } = await sb.from('project_refunds').update({ status: status }).eq('id', id);
      if (error) { console.error('DB projectRefunds.updateStatus:', error); return false; }
      return true;
    },
    async updateNotes(id, notes) {
      var sb = getSupabase();
      if (!sb) return false;
      var { error } = await sb.from('project_refunds').update({ notes: notes }).eq('id', id);
      if (error) { console.error('DB projectRefunds.updateNotes:', error); return false; }
      return true;
    }
  },

  // ---------- PROJECT DISBURSEMENTS (Phase 2) ----------
  projectDisbursements: {
    async getByProject(projectId) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('project_disbursements').select('*').eq('project_id', projectId).order('created_at', { ascending: false });
      if (error) { console.error('DB projectDisbursements.getByProject:', error); return null; }
      return data;
    },
    async create(db) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('project_disbursements').insert(db).select().single();
      if (error) { console.error('DB projectDisbursements.create:', error); return null; }
      return data;
    },
    async updateStatus(id, status) {
      var sb = getSupabase();
      if (!sb) return false;
      var { error } = await sb.from('project_disbursements').update({ status: status }).eq('id', id);
      if (error) { console.error('DB projectDisbursements.updateStatus:', error); return false; }
      return true;
    },
    async updateNotes(id, notes) {
      var sb = getSupabase();
      if (!sb) return false;
      var { error } = await sb.from('project_disbursements').update({ notes: notes }).eq('id', id);
      if (error) { console.error('DB projectDisbursements.updateNotes:', error); return false; }
      return true;
    }
  },

  // ---------- PROJECT FINANCIAL SUMMARIES (Phase 2) ----------
  projectFinancialSummaries: {
    async getAll() {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.rpc('get_all_financial_summaries');
      if (error) { console.error('DB projectFinancialSummaries.getAll:', error); return null; }
      return data;
    },
    async getByProject(projectId) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.rpc('get_project_financial_summary', { p_project_id: projectId });
      if (error) { console.error('DB projectFinancialSummaries.getByProject:', error); return null; }
      // RPC returns SETOF — extract the first row. Returns null if no summary exists yet.
      return (data && data.length > 0) ? data[0] : null;
    }
  },

  // ---------- INVESTOR HUB — Phase 2B ----------
  // RULE: No delete methods. Use cancel / status instead.
  // RULE: Does NOT write to project_expenses, project_refunds,
  //       project_disbursements, or project_financial_summaries.

  investors: {
    async getAll() {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('investors').select('*').order('name', { ascending: true });
      if (error) { console.error('DB investors.getAll:', error); return null; }
      return data;
    },
    async getById(id) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('investors').select('*').eq('id', id).single();
      if (error) { console.error('DB investors.getById:', error); return null; }
      return data;
    },
    async create(inv) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('investors').insert({
        name:       (inv.name || '').trim(),
        type:       inv.type || 'person',
        company_id: inv.company_id || null,
        email:      inv.email || '',
        phone:      inv.phone || '',
        status:     inv.status || 'active',
        notes:      inv.notes || ''
      }).select().single();
      if (error) { console.error('DB investors.create:', error); return null; }
      return data;
    },
    async updateStatus(id, status) {
      var sb = getSupabase();
      if (!sb) return false;
      var { error } = await sb.from('investors').update({ status: status }).eq('id', id);
      if (error) { console.error('DB investors.updateStatus:', error); return false; }
      return true;
    },
    async updateNotes(id, notes) {
      var sb = getSupabase();
      if (!sb) return false;
      var { error } = await sb.from('investors').update({ notes: notes }).eq('id', id);
      if (error) { console.error('DB investors.updateNotes:', error); return false; }
      return true;
    }
    // No delete method — use updateStatus('inactive') instead.
  },

  investorCompanies: {
    async getAll() {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('investor_companies').select('*').order('company_name', { ascending: true });
      if (error) { console.error('DB investorCompanies.getAll:', error); return null; }
      return data;
    },
    async getById(id) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('investor_companies').select('*').eq('id', id).single();
      if (error) { console.error('DB investorCompanies.getById:', error); return null; }
      return data;
    },
    async create(co) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('investor_companies').insert({
        company_name:   (co.company_name || '').trim(),
        contact_person: co.contact_person || '',
        email:          co.email || '',
        phone:          co.phone || '',
        license_number: co.license_number || '',
        state:          co.state || '',
        notes:          co.notes || ''
      }).select().single();
      if (error) { console.error('DB investorCompanies.create:', error); return null; }
      return data;
    },
    async updateNotes(id, notes) {
      var sb = getSupabase();
      if (!sb) return false;
      var { error } = await sb.from('investor_companies').update({ notes: notes }).eq('id', id);
      if (error) { console.error('DB investorCompanies.updateNotes:', error); return false; }
      return true;
    }
    // No delete method.
  },

  projectInvestors: {
    async getByProject(projectId) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('project_investors')
        .select('*, investors(name, type, email, status)')
        .eq('project_id', projectId)
        .order('created_at', { ascending: true });
      if (error) { console.error('DB projectInvestors.getByProject:', error); return null; }
      return data;
    },
    async attach(projectId, investorId, role, opts) {
      var sb = getSupabase();
      if (!sb) return null;
      opts = opts || {};
      var ownership = opts.ownership_percentage;
      var profitSplit = opts.profit_split_percentage;
      var { data, error } = await sb.from('project_investors').insert({
        project_id:              projectId,
        investor_id:             investorId,
        role:                    role || 'equity_partner',
        ownership_percentage:    ownership === null || ownership === undefined || ownership === '' ? 0 : ownership,
        profit_split_percentage: profitSplit === null || profitSplit === undefined || profitSplit === '' ? 0 : profitSplit,
        status:                  'pending',
        agreement_notes:         opts.agreement_notes || ''
      }).select().single();
      if (error) { console.error('DB projectInvestors.attach:', error); return null; }
      return data;
    },
    async confirm(id) {
      var sb = getSupabase();
      if (!sb) return false;
      var { error } = await sb.from('project_investors').update({ status: 'confirmed' }).eq('id', id);
      if (error) { console.error('DB projectInvestors.confirm:', error); return false; }
      return true;
    },
    async cancel(id) {
      // RULE 2B: No delete. Set status to cancelled.
      var sb = getSupabase();
      if (!sb) return false;
      var { error } = await sb.from('project_investors').update({ status: 'cancelled' }).eq('id', id);
      if (error) { console.error('DB projectInvestors.cancel:', error); return false; }
      return true;
    }
    // No delete method.
  },

  capitalContributions: {
    async getByProject(projectId) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('capital_contributions')
        .select('*, investors(name, type)')
        .eq('project_id', projectId)
        .order('date', { ascending: false });
      if (error) { console.error('DB capitalContributions.getByProject:', error); return null; }
      return data;
    },
    async getByInvestor(projectId, investorId) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('capital_contributions')
        .select('*')
        .eq('project_id', projectId)
        .eq('investor_id', investorId)
        .order('date', { ascending: false });
      if (error) { console.error('DB capitalContributions.getByInvestor:', error); return null; }
      return data;
    },
    async getTotalConfirmedByProject(projectId) {
      var sb = getSupabase();
      if (!sb) return 0;
      var { data, error } = await sb.from('capital_contributions')
        .select('amount')
        .eq('project_id', projectId)
        .eq('status', 'confirmed');
      if (error) { console.error('DB capitalContributions.getTotalConfirmedByProject:', error); return 0; }
      return (data || []).reduce(function(sum, r) { return sum + (parseFloat(r.amount) || 0); }, 0);
    },
    async create(contrib) {
      var sb = getSupabase();
      if (!sb) return null;
      // RULE: Validate amount > 0 in JS before sending to DB
      var amt = parseFloat(contrib.amount) || 0;
      if (amt <= 0) { console.error('DB capitalContributions.create: amount must be > 0'); return null; }
      var { data, error } = await sb.from('capital_contributions').insert({
        project_id:         contrib.project_id,
        investor_id:        contrib.investor_id,
        amount:             amt,
        date:               contrib.date,
        method:             contrib.method || 'wire',
        type:               contrib.type || 'initial',
        status:             'pending',
        evidence_reference: contrib.evidence_reference || '',
        notes:              contrib.notes || ''
      }).select().single();
      if (error) { console.error('DB capitalContributions.create:', error); return null; }
      return data;
    },
    async confirm(id) {
      var sb = getSupabase();
      if (!sb) return false;
      var { error } = await sb.from('capital_contributions').update({ status: 'confirmed' }).eq('id', id);
      if (error) { console.error('DB capitalContributions.confirm:', error); return false; }
      return true;
    },
    async cancel(id) {
      // RULE 2B: No delete. Set status to cancelled. Historical data preserved.
      var sb = getSupabase();
      if (!sb) return false;
      var { error } = await sb.from('capital_contributions').update({ status: 'cancelled' }).eq('id', id);
      if (error) { console.error('DB capitalContributions.cancel:', error); return false; }
      return true;
    }
    // No delete method — DB trigger also blocks DELETE.
    // To correct a wrong amount: cancel this record, create a new one.
  },

  capitalCalls: {
    async getByProject(projectId) {
      var sb = getSupabase();
      if (!sb) return null;
      var { data, error } = await sb.from('capital_calls')
        .select('*')
        .eq('project_id', projectId)
        .order('created_at', { ascending: false });
      if (error) { console.error('DB capitalCalls.getByProject:', error); return null; }
      return data;
    },
    async create(call) {
      var sb = getSupabase();
      if (!sb) return null;
      var amt = parseFloat(call.requested_amount) || 0;
      if (amt <= 0) { console.error('DB capitalCalls.create: requested_amount must be > 0'); return null; }
      var { data, error } = await sb.from('capital_calls').insert({
        project_id:       call.project_id,
        requested_amount: amt,
        reason:           (call.reason || '').trim(),
        due_date:         call.due_date || null,
        status:           'pending',
        notes:            call.notes || ''
      }).select().single();
      if (error) { console.error('DB capitalCalls.create:', error); return null; }
      return data;
    },
    async confirm(id) {
      var sb = getSupabase();
      if (!sb) return false;
      var { error } = await sb.from('capital_calls').update({ status: 'confirmed' }).eq('id', id);
      if (error) { console.error('DB capitalCalls.confirm:', error); return false; }
      return true;
    },
    async cancel(id) {
      var sb = getSupabase();
      if (!sb) return false;
      var { error } = await sb.from('capital_calls').update({ status: 'cancelled' }).eq('id', id);
      if (error) { console.error('DB capitalCalls.cancel:', error); return false; }
      return true;
    }
    // No delete method.
  },

  // ---------- SEED DEFAULTS ----------
  async seedIfEmpty() {
    var sb = getSupabase();
    if (!sb) return;
    // Check if services table is empty
    var { count } = await sb.from('services').select('id', { count: 'exact', head: true });
    if (count === 0 && typeof _DEFAULT_SERVICES !== 'undefined') {
      console.log('Seeding default services...');
      await this.services.bulkInsert(_DEFAULT_SERVICES);
    }
    // Check if clients table is empty
    var { count: cCount } = await sb.from('clients').select('id', { count: 'exact', head: true });
    if (cCount === 0 && typeof _DEFAULT_CLIENTS !== 'undefined') {
      console.log('Seeding default clients...');
      for (var i = 0; i < _DEFAULT_CLIENTS.length; i++) {
        await this.clients.create(_DEFAULT_CLIENTS[i]);
      }
    }
    // Check if work orders table is empty
    var { count: wCount } = await sb.from('work_orders').select('id', { count: 'exact', head: true });
    if (wCount === 0 && typeof _DEFAULT_WORK_ORDERS !== 'undefined') {
      console.log('Seeding default work orders...');
      for (var i = 0; i < _DEFAULT_WORK_ORDERS.length; i++) {
        await this.workOrders.create(_DEFAULT_WORK_ORDERS[i]);
      }
    }
  }
};

// ============================================================
// INVESTOR HUB — Phase 2B
// ============================================================

// InvestorManager para gestionar inversores y análisis de flips
let investorMgr = null;

function getInvestorManager() {
  if (investorMgr) return investorMgr;
  var sb = getSupabase();
  if (!sb) return null;
  // InvestorManager será importado via script tag en HTML
  if (typeof InvestorManager === 'undefined') return null;
  investorMgr = new InvestorManager(sb);
  return investorMgr;
}

function isInvestorManagerReady() {
  return !!getInvestorManager();
}
